import type { ComplianceParityFixture } from "./types";

export const standardFixture: ComplianceParityFixture = {
  id: "standard-invoice",
  title: "Standard Invoice",
  expectedValidation: "PASSED",
  strictParity: true,
  invoice: {
    invoiceNumber: "INV-PARITY-STD-0001",
    invoiceKind: "STANDARD",
    submissionFlow: "CLEARANCE",
    issueDateIso: "2026-04-22T10:30:00",
    currencyCode: "SAR",
    seller: {
      registrationName: "Maximum Speed Tech Supply LTD",
      taxNumber: "399999999900003",
      registrationNumber: "1010010000",
      address: {
        streetName: "Prince Sultan",
        buildingNumber: "2322",
        citySubdivisionName: "Al Murabba",
        additionalStreetName: "Al Murabba",
        cityName: "Riyadh",
        postalZone: "23333",
        countryCode: "SA",
      },
    },
    buyer: {
      registrationName: "Fatoora Samples LTD",
      taxNumber: "399999999800003",
      registrationNumber: "1010020000",
      address: {
        streetName: "Salah Al-Din",
        buildingNumber: "1111",
        citySubdivisionName: "Al Murooj",
        additionalStreetName: "Al Murooj",
        cityName: "Riyadh",
        postalZone: "12222",
        countryCode: "SA",
      },
    },
    deliveryDateIso: "2026-04-22T10:30:00.000Z",
    paymentMeansCode: "30",
    subtotal: "250.00",
    taxTotal: "37.50",
    total: "287.50",
    note: "Standard parity fixture",
    lines: [
      {
        description: "Networking equipment",
        quantity: "2.00",
        unitPrice: "100.00",
        lineExtensionAmount: "200.00",
        taxAmount: "30.00",
        taxRatePercent: "15.00",
        taxRateName: "VAT 15%",
      },
      {
        description: "Support service",
        quantity: "1.00",
        unitPrice: "50.00",
        lineExtensionAmount: "50.00",
        taxAmount: "7.50",
        taxRatePercent: "15.00",
        taxRateName: "VAT 15%",
      },
    ],
  },
};
